### ISSUE TITLE
Remind of ICRA22 - RINet

### ISSUE THREAD

**Issue by kxhit** [Taeyoung96/ICRA-2022-SLAM-paper-list#2]
Hi thanks for the ICRA2022 repo.

I just want to kindly remind of our paper "[RINet: Efficient 3D Lidar-Based Place Recognition Using Rotation Invariant Neural Network](https://ieeexplore.ieee.org/document/9712221)" for LiDAR based place recognition with open-sourced code [here](https://github.com/lilin-hitcrt/RINet).

Thanks.

**Comment by Taeyoung96** [comment]
Hi,  
Thanks for sharing your great work!  
I'll add "RINet" to "LiDAR place recognition part.  
Thanks, :+1:
